MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "/home/guli/Desktop/VOS_ICCV2019/maskrcnn-benchmark/pretrained_weight/model_0359999.pth"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
    OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 2
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
#    LOSS: "Balanced"
  MASK_ON: True
INPUT:
  PIXEL_MEAN: [122.7175, 120.6902, 117.5148]
DATASETS:
  TRAIN: ("DAVIS_train_instance_id",)
  TEST: ("DAVIS_valid_instance_id",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.00005
  WEIGHT_DECAY: 0.00001
  STEPS: [0, 8000]
  MAX_ITER: 10000
  CHECKPOINT_PERIOD: 1000
  VALIDATION_PERIOD: 1000
  IMS_PER_BATCH: 4
TRAIN:
  USE_GT_BOX: True
TEST:
  IMS_PER_BATCH: 2
  DEBUG: False
  OVERLAY_BOX: False
  MATCHING: False

EXP:
  NAME: "Train_DAVIS_0.00005_2GPUS_baseline_gt_box"
