MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
#  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  WEIGHT: "//home/guli/Desktop/VOS_ICCV2019/maskrcnn-benchmark/pretrained_weight/e2e_mask_rcnn_R_50_FPN_1x.pth"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
    OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
  MASK_ON: True
DATASETS:
#  TRAIN: ("coco_2014_train", "coco_2014_valminusminival")
#  TEST: ("coco_2014_val",)
   TRAIN: ("coco_2017_train", )
   TEST: ("coco_2017_val",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
#  BASE_LR: 0.0025
  BASE_LR: 0.000025
  WEIGHT_DECAY: 0.0001
  STEPS:  [0, 240000, 320000]
  MAX_ITER: 360000
  CHECKPOINT_PERIOD: 10000
  VALIDATION_PERIOD: 10000
  IMS_PER_BATCH: 2
TEST:
  IMS_PER_BATCH: 8
  SKIP_TRAIN: False
EXP:
  NAME: "COCO_2014_1x"
